# Site settings
author: Jade Lynn Masker
title: The Hopeful Fire
header-img: img/home-bg.png
email: hopefulfire@gmail.com
copyright_name: Jade Lynn Masker
description: > # this means to ignore newlines until "baseurl:"
  A budding programmer's blog.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HopefulFire

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
